import React, { useState, useEffect, useRef } from 'react';
import { Header } from './components/Header';
import { MessageBubble } from './components/MessageBubble';
import { InputArea } from './components/InputArea';
import { ApiKeyModal } from './components/ApiKeyModal';
import { Message } from './types';
import { sendMessageToGemini } from './services/geminiService';
import { Lock } from 'lucide-react';

export default function App() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 'welcome-1',
      text: "Hello! I am Doc-Talk, your multilingual AI health assistant.You can chat with me in any language.Ask me any health question, or simply send a photo 📷 of a medicine or symptom for instant advice.",
      sender: 'bot',
      timestamp: new Date(),
      status: 'read'
    }
  ]);
  const [isTyping, setIsTyping] = useState(false);
  const [apiKey, setApiKey] = useState<string>('');
  const [showKeyModal, setShowKeyModal] = useState(false);
  
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Initialize API Key logic
  useEffect(() => {
    // 1. Check Environment Variable (Developer Mode)
    const envKey = process.env.API_KEY;
    if (envKey) {
        setApiKey(envKey);
        return;
    }

    // 2. Check Local Storage (User Mode)
    const storedKey = localStorage.getItem('gemini_api_key');
    if (storedKey) {
        setApiKey(storedKey);
    } else {
        // 3. Prompt User
        setShowKeyModal(true);
    }
  }, []);

  const handleSaveKey = (key: string) => {
      localStorage.setItem('gemini_api_key', key);
      setApiKey(key);
      setShowKeyModal(false);
  };

  const handleClearKey = () => {
      localStorage.removeItem('gemini_api_key');
      setApiKey('');
      setShowKeyModal(true);
      // Optional: Reset chat
      setMessages([{
        id: 'welcome-1',
        text: "👋 Key cleared. Please enter a new API Key to continue.",
        sender: 'bot',
        timestamp: new Date(),
        status: 'read'
      }]);
  };

  // Auto-scroll to bottom on new message
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  const handleSendMessage = async (text: string, image?: string) => {
    // 1. Add User Message
    const userMsg: Message = {
      id: Date.now().toString(),
      text: text,
      image: image,
      sender: 'user',
      timestamp: new Date(),
      status: 'sent'
    };
    
    setMessages(prev => [...prev, userMsg]);
    setIsTyping(true);

    // Simulate "delivered" tick after a moment
    setTimeout(() => {
        setMessages(prev => prev.map(m => m.id === userMsg.id ? {...m, status: 'delivered' as const} : m));
    }, 1000);

    // 2. Call Gemini API
    const botResponseText = await sendMessageToGemini(text, image, apiKey);

    // 3. Add Bot Message
    const botMsg: Message = {
      id: (Date.now() + 1).toString(),
      text: botResponseText,
      sender: 'bot',
      timestamp: new Date(),
      status: 'read' // Bot messages don't really have status, but for type consistency
    };

    setIsTyping(false);
    setMessages(prev => {
        // Mark user message as read when bot replies
        const updatedMessages = prev.map(m => m.id === userMsg.id ? {...m, status: 'read' as const} : m);
        return [...updatedMessages, botMsg];
    });
  };

  return (
    <div className="flex justify-center bg-[#111b21] min-h-screen font-sans">
      <div className="w-full max-w-[500px] h-screen bg-[#e5ddd5] bg-whatsapp-pattern flex flex-col shadow-2xl overflow-hidden relative">
        
        <Header onSettingsClick={handleClearKey} />

        <ApiKeyModal isOpen={showKeyModal} onSave={handleSaveKey} />

        {/* Chat Area */}
        <div className="flex-1 overflow-y-auto p-4 md:p-5 scrollbar-hide relative z-0">
          
          {/* Encryption Notice */}
          <div className="flex justify-center mb-6">
            <div className="bg-[#ffeecd] text-[10px] md:text-xs text-[#54656f] px-3 py-1.5 rounded-lg shadow-sm flex items-center gap-1.5 text-center max-w-[90%]">
                <Lock size={10} className="shrink-0" />
                <span>Messages are generated by AI. Do not rely on them for emergencies.</span>
            </div>
          </div>

          {messages.map((msg) => (
            <MessageBubble key={msg.id} message={msg} />
          ))}
          
          {isTyping && (
             <div className="flex justify-start mb-3 animate-pulse">
                <div className="bg-white rounded-lg rounded-tl-none p-3 shadow-sm text-gray-500 text-sm flex items-center gap-1">
                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce"></span>
                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce delay-100"></span>
                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce delay-200"></span>
                </div>
             </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <InputArea onSendMessage={handleSendMessage} isTyping={isTyping} />
      </div>
    </div>
  );
}